### PR TITLE
Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

### PR DESCRIPTION
**Pull request by carusogabriel**
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).

Also, set the minimum version of PHPUnit for [4.8.36](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21), that contains these namespaces support.

### CODE REVIEW

**Comment by wilsonge** [comment]
You need to bump the minimum PHPUnit version if you want to do this. That class has only existed since PHP 5.4.3 https://github.com/sebastianbergmann/phpunit/blob/aa47f767c5ecadab9df0862c34398e4ee582bb56/ChangeLog-5.4.md#543---2016-06-09

**Comment by gabriel-caruso** [comment]
@wilsonge Actually, was [4.8.36](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4836---2017-06-21). But thanks for the advise, I'll require it.

**Comment by JakubOleksy** [comment]
Can you review the conflicts?

**Comment by carusogabriel** [comment]
@JakubOleksy Done :+1:

**Pull request merged**
