### PR TITLE
Enable Async Tracking

### PR DESCRIPTION
**Pull request by jondmcelroy**
increase the extensibility of Telemetry_Channel
a response/promise is returned from the flush

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@jondmcelroy can you please add a test for the this extensibility?

**Comment by SergeyKanzhelev** [comment]
@JakubOleksy does it looks OK for you to merge?

**Comment by JakubOleksy** [comment]
Yes, sorry for the delay.

**Comment by jondmcelroy** [comment]
@JakubOleksy  Don't forget to close: https://github.com/Microsoft/ApplicationInsights-PHP/issues/26
Thanks!

**Pull request merged**
